spring:
  application:
    name: Gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: volunteer-service
          uri: lb://volunteer-service
          predicates:
              - Path=/api/volunteer/**

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public-key.pem


eureka:
    client:
        service-url:
          defaultZone: http://localhost:${EUREKA_PORT:8761}/eureka/

server:
  port: ${GATEWAY_PORT:8080}

# Custom variables

security:
  jwt:
    secret: ${JWT_SECRET:my-super-secret-key-for-signing-tokens-yay}
    expiration: ${JWT_EXPIRATION_MS:3600000} # 1 hour
    refresh-expiration: ${JWT_REFRESH_EXPIRATION_MS:86400000} # 24 hours