spring:
  application:
    name: VolunteerServer


  # JPA and Hibernate configuration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  # Database configuration

  datasource:
    url: jdbc:postgresql://127.0.0.1:${PORT_DATABASE_VOLUNTEER:5552}/Volunteers
    username: ${POSTGRES_USER:vpm-dev}
    password: ${POSTGRES_PASSWORD:password}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: ${PORT_VOLUNTEER_SERVICE:8082}