spring:
  application:
    name: project-service


  # JPA and Hibernate configuration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  # Database configuration

  datasource:
    url: jdbc:postgresql://127.0.0.1:${PORT_DATABASE_PROJECT:5554}/Projects
    username: ${POSTGRES_USER:vpm-dev}
    password: ${POSTGRES_PASSWORD:password}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  # RabbitMQ configuration

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:password}

    publisher-confirm-type: correlated
    publisher-returns: true

    # configuration variables
    queue:
      volunteer-assigned: queue.volunteer-project
      dlq:
        volunteer-assigned: dlq.volunteer-project

    exchange:
      volunteer-assigned: exchange.volunteer-project
      dlx:
        volunteer-assigned: dlx.volunteer-project

    routing-key:
      volunteer-assigned: volunteer-project.assigned
      dlq:
          volunteer-assigned: dlq.volunteer-project.assigned


server:
  port: ${PORT_PROJECT_SERVICE:8084}